// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb9gzEwQLwWhyiuoJbbPr2j-ZD6_00L3g',
    appId: '1:1097152257298:web:b0ae700de71a7d7b5367cb',
    messagingSenderId: '1097152257298',
    projectId: 'hahaha-13315',
    authDomain: 'hahaha-13315.firebaseapp.com',
    storageBucket: 'hahaha-13315.firebasestorage.app',
    measurementId: 'G-EK1547J1CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXXMoShAqDaUh5k0jF7MXJaJ5fGGh5agY',
    appId: '1:1097152257298:android:9f9d3469aebe2fe35367cb',
    messagingSenderId: '1097152257298',
    projectId: 'hahaha-13315',
    storageBucket: 'hahaha-13315.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQMEB5FvxI4SGj3Slg9i5X8dfP5L_Eq_0',
    appId: '1:1097152257298:ios:c340f4bc559db11c5367cb',
    messagingSenderId: '1097152257298',
    projectId: 'hahaha-13315',
    storageBucket: 'hahaha-13315.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
